### ISSUE TITLE
Error in “grayscale = tf.concat(3, [grayscale, grayscale, grayscale])”

### ISSUE THREAD

**Issue by wbwz1992** [pavelgonchar/colornet#12]
This error info：
Traceback (most recent call last):
  File "E:\robin\ColorNet\train.py", line 131, in <module>
    grayscale = tf.concat(3, [grayscale, grayscale, grayscale])
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "D:\ProgramFiles\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Anybody have meet this problem？How to solve？

**Comment by zero1hac** [comment]
@wbwz1992 Which version of Tensorflow are you running?

**Comment by zyzn** [comment]
I met the same problem, how to solve?

**Comment by zyzn** [comment]
@wbwz1992 I fixed it. Change your code from tf.concat(3, [grayscale, grayscale, grayscale]) to tf.concat([grayscale, grayscale, grayscale], 3)
Because after tensorflow1.0 version, api defines that number is in the last
