### ISSUE TITLE
error Traceback (most recent call last):   File "train.py", line 160, in <module>     graph_def.ParseFromString(fileContent) google.protobuf.message.DecodeError: Error parsing messag

### ISSUE THREAD

**Issue by GANGREEK** [pavelgonchar/colornet#13]
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    graph_def.ParseFromString(fileContent)
google.protobuf.message.DecodeError: Error parsing messag

**Comment by martafd** [comment]
@nandyadav 
```shell
cd vgg/tensorflow-vgg16/
rm vgg16-20160129.tfmodel
wget https://github.com/pavelgonchar/colornet/raw/master/vgg/tensorflow-vgg16/vgg16-20160129.tfmodel
```

**Comment by wunengguang** [comment]
hello, you give website "https://github.com/pavelgonchar/colornet/raw/master/vgg/tensorflow-vgg16/vgg16-20160129.tfmodel" . It do not work now ! please you may give us new website

**Comment by RibbonsAlmark** [comment]
> @nandyadav
> 
> ```shell
> cd vgg/tensorflow-vgg16/
> rm vgg16-20160129.tfmodel
> wget https://github.com/pavelgonchar/colornet/raw/master/vgg/tensorflow-vgg16/vgg16-20160129.tfmodel
> ```

thanks for your advice,but another error appear after I solved this one:

Traceback (most recent call last):
  File "train.py", line 179, in <module>
    colorimage = input_pipeline(filenames, batch_size, num_epochs=num_epochs)
  File "train.py", line 31, in input_pipeline
    filenames, num_epochs=num_epochs, shuffle=False)
  File "/root/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 259, in string_input_producer
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor

**Comment by RibbonsAlmark** [comment]
> @nandyadav
> 
> ```shell
> cd vgg/tensorflow-vgg16/
> rm vgg16-20160129.tfmodel
> wget https://github.com/pavelgonchar/colornet/raw/master/vgg/tensorflow-vgg16/vgg16-20160129.tfmodel
> ```

thanks for your advice,it do fix this bug.but another error appear:

Traceback (most recent call last):
File "train.py", line 179, in 
colorimage = input_pipeline(filenames, batch_size, num_epochs=num_epochs)
File "train.py", line 31, in input_pipeline
filenames, num_epochs=num_epochs, shuffle=False)
File "/root/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
return func(*args, **kwargs)
File "/root/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 259, in string_input_producer
raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor
